  name: Deploy to GitHub Pages
  
  on:
    push:
      branches:
        - master
  
  jobs:
    deploy:
      environment:
        name: github-pages
        url: https://github.com
      runs-on: ubuntu-latest
      env:  
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
